### ISSUE TITLE
Arena Starting Timer - Should be 1 Minute Instead of 40 Seconds

### ISSUE THREAD

**Issue by boktai1000** [BigWigsMods/Capping#106]
## Describe the problem
For Arena matches, the timer starts at 40 seconds.

### What steps will reproduce the problem?

Join a Rated Arena match (did not test Skirmish)

### What version of the addon are you using? (Stating 'latest' is not useful)
v1-bcc

### Any additional information? (example: WoW language if not English)
The timer goes away after 40 seconds while you are still waiting for the doors to open. There are Blizzard system chat messages stating how much time until your match starts, starting with one minute, then thirty seconds, then fifteen seconds.

**Comment by boktai1000** [comment]
I'm including a picture that shows the discrepancy when compared against DBM-PVP. This is in an Arena Skirmish match.

It seems like the time doesn't automatically correct itself based off of the Blizzard messages for 30 seconds left, 15 seconds left, etc which might be useful to use as a basis for an accurate prediction until game start.

![image](https://user-images.githubusercontent.com/9054563/184266138-171ad1a1-7dad-46cb-939b-9871380ab307.png)

**Comment by funkydude** [comment]
I'm actually surprised the timer shows up at all in Capping as it was coded for the way retail handles it (showing the timer at the top of the screen) so somehow that event still triggers but with a wrong timer. (we don't hard code what the time remaining is)

Thanks for the detailed info. I will need to revisit all this for wotlk support very soon, with a rewrite to support multi toc instead of multiple zip hell we currently have. I doubt I'll fix this for BCC since it's being dropped by Blizz, but leaving this open so we can verify if it's still a problem in wotlk.
