### ISSUE TITLE
Timers out for EoTS start

### ISSUE THREAD

**Issue by Tsubear** [BigWigsMods/Capping#107]
The timer for the start of EoTS is 15 seconds too soon.

**Comment by boktai1000** [comment]
Here's a screenshot of the discrepancy between Capping and DBM-PVP showing the start times for Eye of the Storm on BC Classic

![image](https://user-images.githubusercontent.com/9054563/184400271-5835c5d3-0110-472d-9deb-04a1617ac7ea.png)

![image](https://user-images.githubusercontent.com/9054563/184400326-2a5bcb0c-8ea7-4420-af60-313bbbad1948.png)

![image](https://user-images.githubusercontent.com/9054563/184400449-38753425-3d17-4871-8250-80267c67fed0.png)

**Comment by funkydude** [comment]
@boktai1000 Similar to your report about arenas, our code here is generic, with Blizz telling us what the start time is.

This code is the same across all BGs. Are you saying the start timers for other BGs are fine and this only affects EoTS?

**Comment by boktai1000** [comment]
@funkydude I did see there was an open issue https://github.com/BigWigsMods/Capping/issues/111 regarding multiple BG timers being off (with the tag referring to BC Classic).

I haven't had a chance to go through all of them, but I'm leaning to think that perhaps the issue is correct in identifying the problem across the board, I just haven't had a chance to test / verify my own findings regarding it just yet and have been working through validating things.

If you have any suggestions as to how you might want to receive information and what tests to perform, I'd be happy to help in the context of BC Classic and get that information back to you (Not sure if PVP testing is live on Wrath Beta / PTR - but unsure how different it would be)

Thanks again and happy to help however I can!
